### ISSUE TITLE
Remove RP Image

### ISSUE THREAD

**Issue by pranaygp** [acm-uiuc/display#4]
We should remove the R|P Banner now that R|P has ended. @sskhandek , is that cool?

**Comment by sskhandek** [comment]
@pranaygp I already deleted it

**Comment by pranaygp** [comment]
@sskhandek Okay, ignore that then. I just saw it here so I mentioned it. Should be fixed now.

**Comment by kevinwang** [comment]
Thanks @sskhandek. In the future I recommend making a PR so I know to pull in any changes.

**Comment by sskhandek** [comment]
@kevinwang Yeah I realized that was bad etiquette. My b
