### ISSUE TITLE
Add 3Red Logo

### ISSUE THREAD

**Issue by bcongdon** [acm-uiuc/display#9]
Need to add 3Red to the list of scrolling sponsors.

https://github.com/acm-uiuc/groot-desktop-frontend/blob/master/public/images/sponsors/3red.jpg

**Comment by kevinwang** [comment]
Is the JPEG image the only one available? I prefer lossless formats for logos, but if this is all they provided to you then it's fine.

@tyler-thetyrant What is the sponsorship level?

**Comment by tyler-thetyrant** [comment]
Silver. 
Yeah, I actually got the 3red logo from the wcs's display repo as I couldn't find a better one online.
